# Remote data source configuration
remote:
  goodreads_data: "https://mcauleylab.ucsd.edu/public_datasets/gdrive/goodreads"
  bookdata: "https://mcauleylab.ucsd.edu/public_datasets/gdrive/goodreads/goodreads_books.json.gz"
  reviewdata: "https://mcauleylab.ucsd.edu/public_datasets/gdrive/goodreads/goodreads_reviews_deduped.json.gz"
# Local file paths
paths:
  raw_book_data: "data/raw/goodreads_books.json.gz"
  raw_review_data: "data/raw/goodreads_reviews_dedup.json.gz"
  filtered_book_data: "data/scifi_fantasy.json.gz"
  filtered_review_data: "data/scifi_fantasy_reviews.json.gz"

# Filter configuration
filter:
  genres: ["fantasy", "scifi", "science fiction"] 
  ratings_threshold: 1000
  tag_threshold: 0.05