# Remote data source configuration
remote:
  goodreads_data_root: "https://mcauleylab.ucsd.edu/public_datasets/gdrive/goodreads"


# Local file paths
paths:
  basenames:
    book_data: "goodreads_books.json.gz"
    author_data: "goodreads_book_authors.json.gz"
    works_data: "goodreads_book_works.json.gz"
    awards_data: "awards.json"
    award_counts_data: "award_counts.csv"
    selected_works_data: "sff_works.parquet"
    augmented_works_data: "sff_works_augmented.parquet"
    cleaned_awards_data: "awards.csv"
    identifiers_data: "identifiers.parquet"
  roots:
    data: "data"
    raw_data: "data/raw"

# Filter configuration
filter:
  ratings_threshold: 100
  tag_threshold: 2