# Remote data source configuration
remote:
  goodreads_data: "https://mcauleylab.ucsd.edu/public_datasets/gdrive/goodreads"
  bookdata: "https://mcauleylab.ucsd.edu/public_datasets/gdrive/goodreads/goodreads_books.json.gz"
  reviewdata: "https://mcauleylab.ucsd.edu/public_datasets/gdrive/goodreads/goodreads_reviews_deduped.json.gz"
# Local file paths
paths:
  raw_book_data: "data/raw/goodreads_books.json.gz"
  raw_works_data: "data/raw/goodreads_book_works.json.gz"
  raw_author_data: "data/raw/goodreads_book_authors.json.gz"
  raw_awards_data: "data/raw/awards.json"
  selected_works_data: "data/sff_works.parquet"
  augmented_works_data: "data/sff_works_augmented.parquet"
  cleaned_awards_data: "data/awards.json"

# Filter configuration
filter:
  genres: ["fantasy", "scifi", "science fiction"] 
  ratings_threshold: 1000
  tag_threshold: 0.05