# Remote data source configuration
remote:
  goodreads_data_root: "https://mcauleylab.ucsd.edu/public_datasets/gdrive/goodreads"


# Local file paths
paths:
  basenames:
    # Raw bibliographic data
    book_data: "goodreads_books.json.gz"
    author_data: "goodreads_book_authors.json.gz"
    works_data: "goodreads_book_works.json.gz"

    # Raw awards data
    awards_data: "awards.json"
    all_winners_data: "all_winners.json"
    nominee_biographical_data: "nominee_biographical.json"

    # Helpful Lookups
    identifiers_data: "identifiers.parquet"

    # Processed data
    selected_works_data: "sff_works.parquet"
    augmented_works_data: "sff_works_augmented.parquet"
    cleaned_awards_data: "awards.csv"

  roots:
    data: "data"
    raw_data: "data/raw"

# Filter configuration
filter:
  ratings_threshold: 100
  tag_threshold: 2