[workspace]
authors = ["Zach Raines <dev@zmraines.com>"]
channels = ["conda-forge", "bioconda"]
name = "GoodReads"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
scikit-learn = ">=1.6.1,<2"
pandas = ">=2.2.3,<3"
matplotlib = ">=3.10.3,<4"
numpy = ">=2.2.5,<3"
scipy = ">=1.15.2,<2"
seaborn = ">=0.13.2,<0.14"
jupyter = ">=1.1.1,<2"
statsmodels = ">=0.14.4,<0.15"
jupyterlab = ">=4.4.2,<5"
jupyterlab_vim = ">=4.1.4,<5"
jupyterlab-lsp = ">=5.1.0,<6"
pixi-pycharm = ">=0.0.8,<0.0.9"
w3lib = ">=2.3.1,<3"
snakemake = { version = ">=9,<10", channel = "bioconda" }
python-lsp-server = ">=1.12.2,<2"
snakemake-storage-plugin-http = ">=0.3.0,<0.4"
tqdm = ">=4.67.1,<5"
python-isal = ">=1.7.2,<2"
pyarrow = ">=20.0.0,<21"
modin = ">=0.30.0,<0.31"
duckdb-cli = ">=1.2.2,<2"
sparqlwrapper = ">=2.0.0,<3"
httpx = ">=0.28.1,<0.29"

[pypi-dependencies]
httpx-retries = ">=0.4.0, <0.5"
